### ISSUE TITLE
Improve

### ISSUE THREAD

**Issue by wizz666** [tzoug/ThingiZIP#1]
Hi. 
This is just an tips and if you can it would be rely good. 
If you can add this in your git, https://github.com/bwees/ThingiverseUnblocked 
Than it is complete :)

**Comment by tzoug** [comment]
This is a great idea. I will take a look.

**Comment by wizz666** [comment]
Ok 😀

**Comment by tzoug** [comment]
From what I understand, what you linked is allowing the download of files without removing adblocker. It's a good fix, but the goal of my extension was to facilitate the download of a zip containing all the files. Thanks for the suggestion though.
